# Generated by Django 4.0.2 on 2022-02-28 14:09

from django.db import migrations, models
import organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organizacja', 'verbose_name_plural': 'Organizacje'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='nip',
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=organizations.models.upload_to),
        ),
        migrations.AddField(
            model_name='organization',
            name='tax_number',
            field=models.CharField(default=5252344078, max_length=20, validators=[organizations.models.validate_tax_number], verbose_name='NIP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(max_length=256, verbose_name='państwo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=256, verbose_name='nazwa'),
        ),
    ]
